config/routes.rb
Rails.application.routes.draw do

   # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], path: '', controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
   devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
     sessions: "admin/sessions"
   }
  
  
  scope module: :public do
    root to: 'homes#top'
    get 'about', to: "homes#about"

    resources :items, only: [:index, :show]

    get 'customers/my_page', to:"customers#show"
    get 'customers/information/edit', to:"customers#edit"
    patch 'customers/information', to:"customers#update"
    get 'customers/unsubscribe', to: "customers#unsubscribe"
    patch 'customers/withdraw', to: "customers#withdraw"

    delete 'cart_items/destroy_all', to: "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
     
    get 'orders/thanks', to: "orders#thanks"
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/confirm', to: "orders#confirm"
    

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    get "search" => "searches#search"
  end

  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :customers, only: [:index, :show, :edit, :update] do
      get 'orders', to: 'orders#customer_index', as: 'customer_orders'
    end
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end
  
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :name, :postal_code, :address, presence: true
  def address_display
    '〒' + self.postal_code + ' ' + self.address + ' ' + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true
  def tax_price
    (self.item.price * 1.1).floor
  end

  def subtotal
    self.tax_price * self.amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :addresses

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :address, presence: true

  validates :postal_code, format: { with: /\A[0-9]+\z/ }
  validates :telephone_number, format: { with: /\A[0-9]+\z/ }

  def active_for_authentication?
    super && is_active == true
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  
  has_many :cart_items
  has_many :order_details
  belongs_to :genre
  
  validates :name, :image, :introduction, :price, presence: true
  validates :is_active, inclusion: { in: [true, false] }
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  scope :genre_search, -> (genre_id) {where(genre_id: genre_id)}

  scope :on_sale, -> {where(is_active: true)}

  def active_status_label
    is_active ? "販売中" : "販売停止中"
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, paid_up: 1, producting: 2, preparing: 3, sented: 4 }

  validates :name, :postal_code, :address, presence: true

  def total_payment
    order_details.sum { |detail| detail.item.price * detail.amount }
  end

  after_update :update_order_detail_status_if_needed

  private

  def update_order_detail_status_if_needed
    if saved_change_to_status? && status == "paid_up"
      self.order_details.update_all(making_status: "pending")
    end
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order


  enum making_status: { unavailable: 0, pending: 1, in_progress: 2, completed: 3 }, _prefix: true

  after_update :update_order_status_if_needed
  after_update :update_order_status_if_all_completed

  private

  # 1つでも制作ステータスを製作中にする⇒注文ステータスを製作中にする
  def update_order_status_if_needed
    if making_status == "in_progress"
      unless order.status == "producting"
        order.update(status: "producting")
      end
    end
  end

  # 全ての製作ステータスを製作完了にする⇒注文ステータスを発送済みにする
  def update_order_status_if_all_completed
    if self.making_status == "completed"
      if order.order_details.all? { |detail| detail.making_status == "completed" }
        order.update(status: "preparing")
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_active)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.order(created_at: :desc).page(params[:page])
    # @order_details = OrderDetail.includes(order: :customer).order(created_at: :desc).page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @genres = Genre.all
    if @item.save
      redirect_to admin_item_path(@item), notice: '商品が登録されました。'
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @genres = Genre.all
    if @item.update(item_params)
      redirect_to admin_item_path(@item), notice: "商品を更新しました。"
    else
      flash.now[:alert] = "更新に失敗しました。"
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id, :price, :image, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :render_404

  private

  def render_404
    render template: 'errors/not_found', status: :not_found
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def genre_search
    @genre_id = params[:genre_id]
    @items = Item.where(genre_id: @genre_id)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container white-bg p-5">

<% if @customer.errors.any? %>
  <div class="alert alert-danger">
    <h6>以下のエラーがあります：</h6>
    <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h4 class="admin-title"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h4>
  <%= form_with model: @customer, url: admin_customer_path(@customer), method: :patch do |f| %>
    <table class="table mt-5 table-borderless ex-admin-table" style="width: 60%;">
      <tr>
      <td style="width: 30%;">会員ID</td>
        <td><%= @customer.id %></td>
      </tr>
      <tr>
        <td>氏名</td>
        <td><%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", class: "form-control" %></td>
        <td><%= f.text_field :first_name, autocomplete: "first_name", class: "form-control" %></td>
      </tr>
      <tr>
        <td>フリガナ</td>
        <td><%= f.text_field :last_name_kana, autocomplete: "last_name_kana", class: "form-control" %></td>
        <td><%= f.text_field :first_name_kana, autocomplete: "first_name_kana", class: "form-control" %></td>
      </tr>
      <tr>
        <td>郵便番号</td>
        <td><%= f.text_field :postal_code, autocomplete: "postal_code", class: "form-control" %></td>
      </tr>
      <tr>
        <td>住所</td>
        <td colspan="4"><%= f.text_field :address, autocomplete: "address", class: "form-control w-100" %></td>
      </tr>
      <tr>
        <td>電話番号</td>
        <td><%= f.text_field :telephone_number, autocomplete: "telephone_number", class: "form-control" %></td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td><%= f.text_field :email, autocomplete: "email", class: "form-control" %></td>
      </tr>
      <tr>
        <td>会員ステータス</td>
        <td>
          <%= f.radio_button :is_active, true %> <%= f.label :is_active, "有効" %>
          <%= f.radio_button :is_active, false %> <%= f.label :is_active, "退会" %>
        </td>
      </tr>
      <tr>
        <td></td>
            <td><%= f.submit "変更を保存", class: "btn btn-success btn-lg", style: "border-radius: 8px;" %>
      </tr>
    </table>
    <% end %>
  </div>

app/views/admin/customers/index.html.erb
<div class="container white-bg p-5">
  <h4 class="admin-title">会員一覧</h4>
  <table class="table mt-5 admin-table table-borderless">
    <thead>
      <tr>
        <th style="width: 10%;">会員ID</th>
        <th style="width: 25%;">氏名</th>
        <th style="width: 45%;">メールアドレス</th>
        <th style="width: 20%;">ステータス</th>
      </tr>
    </thead>

    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td><u><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer), class: "text-dark" %></u></td>
          <td><%= customer.email %></td>
          <td class="<%= customer.is_active ? "text-success font-weight-bold" : "text-secondary font-weight-bold" %>">
            <%= customer.is_active ? "有効" : "退会" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="d-flex justify-content-center">
    <%= paginate @customers %>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container white-bg p-5">
<h4 class="admin-title"><%= @customer.last_name %> <%= @customer.first_name %>さんの会員詳細</h4>
  <table class="table mt-5 table-borderless ex-admin-table">
      <tr>
        <td style="width: 20%;">会員ID</td>
        <td><%= @customer.id %></td>
      </tr>
      <tr>
        <td>氏名</td>
        <td><%= @customer.last_name %> <%= @customer.first_name %></td>
      </tr>
      <tr>
        <td>フリガナ</td>
        <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
      </tr>
      <tr>
        <td>郵便番号</td>
        <td><%= @customer.postal_code %></td>
      </tr>
      <tr>
        <td>住所</td>
        <td><%= @customer.address %></td>
      </tr>
      <tr>
        <td>電話番号</td>
        <td><%= @customer.telephone_number %></td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td><%= @customer.email %></td>
      </tr>
      <tr>
        <td>会員ステータス</td>
        <td class="<%= @customer.is_active ? "text-success font-weight-bold" : "text-secondary font-weight-bold" %>">
          <%= @customer.is_active ? "有効" : "退会" %>
        </td>
      </tr>
      <tr>
        <th></th>
            <td><%= link_to "編集する", edit_admin_customer_path, class: "btn btn-success" %></td>
            <td><%= link_to "注文履歴一覧を見る", admin_root_path, class: "btn btn-primary" %></td>
            <td><%= link_to "#{@customer.last_name}#{@customer.first_name}さんの注文履歴一覧を見る", admin_customer_customer_orders_path(@customer), class: "btn btn-primary" %></td>
          </tr>
    </table>
  </div>