config/routes.rb
Rails.application.routes.draw do

   # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], path: '', controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
   devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
     sessions: "admin/sessions"
   }
  
  
  scope module: :public do
    root to: 'homes#top'
    get 'about', to: "homes#about"

    resources :items, only: [:index, :show]

    get 'customers/my_page', to:"customers#show"
    get 'customers/information/edit', to:"customers#edit"
    patch 'customers/information', to:"customers#update"
    get 'customers/unsubscribe', to: "customers#unsubscribe"
    patch 'customers/withdraw', to: "customers#withdraw"

    delete 'cart_items/destroy_all', to: "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
     
    get 'orders/thanks', to: "orders#thanks"
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/confirm', to: "orders#confirm"
    

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    get "search" => "searches#search"
  end

  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :customers, only: [:index, :show, :edit, :update] do
      get 'orders', to: 'orders#customer_index', as: 'customer_orders'
    end
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end
  
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :name, :postal_code, :address, presence: true
  def address_display
    '〒' + self.postal_code + ' ' + self.address + ' ' + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true
  def tax_price
    (self.item.price * 1.1).floor
  end

  def subtotal
    self.tax_price * self.amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :addresses

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :address, presence: true

  validates :postal_code, format: { with: /\A[0-9]+\z/ }
  validates :telephone_number, format: { with: /\A[0-9]+\z/ }

  def active_for_authentication?
    super && is_active == true
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  
  has_many :cart_items
  has_many :order_details
  belongs_to :genre
  
  validates :name, :image, :introduction, :price, presence: true
  validates :is_active, inclusion: { in: [true, false] }
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  scope :genre_search, -> (genre_id) {where(genre_id: genre_id)}

  scope :on_sale, -> {where(is_active: true)}

  def active_status_label
    is_active ? "販売中" : "販売停止中"
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, paid_up: 1, producting: 2, preparing: 3, sented: 4 }

  validates :name, :postal_code, :address, presence: true

  def total_payment
    order_details.sum { |detail| detail.item.price * detail.amount }
  end

  after_update :update_order_detail_status_if_needed

  private

  def update_order_detail_status_if_needed
    if saved_change_to_status? && status == "paid_up"
      self.order_details.update_all(making_status: "pending")
    end
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order


  enum making_status: { unavailable: 0, pending: 1, in_progress: 2, completed: 3 }, _prefix: true

  after_update :update_order_status_if_needed
  after_update :update_order_status_if_all_completed

  private

  # 1つでも制作ステータスを製作中にする⇒注文ステータスを製作中にする
  def update_order_status_if_needed
    if making_status == "in_progress"
      unless order.status == "producting"
        order.update(status: "producting")
      end
    end
  end

  # 全ての製作ステータスを製作完了にする⇒注文ステータスを発送済みにする
  def update_order_status_if_all_completed
    if self.making_status == "completed"
      if order.order_details.all? { |detail| detail.making_status == "completed" }
        order.update(status: "preparing")
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.order(created_at: :desc).page(params[:page])
    # @order_details = OrderDetail.includes(order: :customer).order(created_at: :desc).page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @genres = Genre.all
    if @item.save
      redirect_to admin_item_path(@item), notice: '商品が登録されました。'
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @genres = Genre.all
    if @item.update(item_params)
      redirect_to admin_item_path(@item), notice: "商品を更新しました。"
    else
      flash.now[:alert] = "更新に失敗しました。"
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id, :price, :image, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @orders = Order.page(params[:page])
  end

  def customer_index
    @customer = Customer.find(params[:customer_id])
    @orders = @customer.orders.order(created_at: :desc).page(params[:page]) 
  end

  def show
    @order = Order.find(params[:id])
    
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_order_path(@order)
  end

  private
  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :render_404

  private

  def render_404
    render template: 'errors/not_found', status: :not_found
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def genre_search
    @genre_id = params[:genre_id]
    @items = Item.where(genre_id: @genre_id)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/orders/customer_index.html.erb
<div class="container white-bg p-5">
  <h4 class="admin-title"><%= "#{@customer.last_name} #{@customer.first_name}" %>さんの注文履歴</h4>
  <table class="table mt-5 admin-table table-borderless">
    <thead>
      <tr>
        <th>購入日時</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><u><%= link_to order.created_at.strftime('%Y/%m/%d %H:%M'), admin_order_path(order), class: "text-dark" %></u></td>
          <td><%= order.order_details.sum(&:amount) %></td>
          <td><%= order.status_i18n %></td> 
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="d-flex justify-content-center">
    <%= paginate @orders %>
  </div>
</div>

app/views/admin/orders/index.html.erb
<!-- 誤って作ってしまったのでいずれ消去します -->



<div class="container my-5">
  <h4 class="bg-light px-4 ml-3 d-inline-block">注文履歴一覧</h4>
  <table class="table mt-5">
    <thead class="thead-light custom-bordered-thead">
      <tr>
      <th>購入日時</th>
      <th>購入者</th>
      <th>注文個数</th>
      <th>注文ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.created_at.strftime('%Y/%m/%d %H:%M') %></td>
          <td><%= "#{order.customer.last_name} #{order.customer.first_name}" %></td>
          <td><%= order.order_details.sum(&:amount) %></td>
          <td><%= order.status_i18n %></td> 
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="d-flex justify-content-center">
    <%= paginate @orders %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container white-bg p-5">
    <h4 class="admin-title">注文履歴詳細</h4>

  <table class="table mt-5 table-borderless ex-admin-table">
    <tr>
      <th style="width: 20%;">購入者</th>
      <td><u><%= link_to @order.customer.last_name + " " + @order.customer.first_name, admin_customer_path(@order.customer), class: "text-dark" %></u></td>
    </tr>
    <tr>
      <th>注文日</th>
      <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
    </tr>
    <tr>
      <th>配送先</th>
      <td>
        <%= @order.postal_code %><%= @order.address %><br>
        <%= "#{@order.customer.last_name} #{@order.customer.first_name}" %>
      </td>
    </tr>
    <tr>
      <th>支払い方法</th>
      <td><%= @order.payment_method_i18n %></td>
    </tr>
    <tr>
      <th>注文ステータス</th>
      <td>
      <%= form_with model: [:admin, @order], url: admin_order_path(@order), method: :patch do |f| %>
        <div class="d-flex align-items-center">
        <%= f.select :status, Order.statuses.keys.map { |k| [I18n.t("enums.order.status.#{k}"), k] } %>
          <%= f.submit "更新", class: "btn btn-success ml-3", style: "border-radius: 8px;" %>
        </div>
      <% end %>
      </td>
      </tr>
  </table>

  <div class="d-flex mt-5" style="align-items: flex-start;">
    <div class="me-4" style="flex: 1;">
      <table class="table mt-4 admin-table table-borderless">
        <thead>
          <tr>
            <th style="width: 30%;">商品名</th>
            <th style="width: 20%;">単価（税込）</th>
            <th style="width: 10%;">数量</th>
            <th style="width: 20%;">小計</th>
            <th style="width: 15%;">制作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= number_with_delimiter((order_detail.item.price * 1.1).floor) %></td>
            <td><%= order_detail.amount %></td>
            <td><%= number_with_delimiter((order_detail.item.price * 1.1 * order_detail.amount).floor) %>
            <td>
            <%= form_with model: [:admin, order_detail], url: admin_order_detail_path(order_detail), method: :patch do |f| %>
              <div class="d-flex align-items-center">
                <%= f.select :making_status, OrderDetail.making_statuses.keys.map { |k| [I18n.t("enums.order_detail.making_status.#{k}"), k] } %>
                <%= f.submit "更新", class: "btn btn-success ml-3", style: "border-radius: 8px;" %>
              </div>
            <% end %>
            </td>
          </tr>
          <% end %>
          </tbody>
      </table>
    </div>

    <div class="align-self-end ml-5">
    <table class="table table-borderless ex-admin-table">
        <tr>
          <th>商品合計</th>
          <td class="text-end"><%= number_with_delimiter((@order.total_payment * 1.1).floor, delimiter: ",") + " 円" %></td>
        </tr>
        <tr>
          <th>送料</th>
          <td class="text-right"><%= number_with_delimiter(@order.shipping_cost)+ " 円" %></td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td class="text-right"><%= number_with_delimiter((@order.total_payment * 1.1 + @order.shipping_cost).floor, delimiter: "," ) + " 円" %></td>
        </tr>
      </table>
    </div>
  </div>
</div>