config/routes.rb
Rails.application.routes.draw do

   # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], path: '', controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
   devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
     sessions: "admin/sessions"
   }
  
  
  scope module: :public do
    root to: 'homes#top'
    get 'about', to: "homes#about"

    resources :items, only: [:index, :show]

    get 'customers/my_page', to:"customers#show"
    get 'customers/information/edit', to:"customers#edit"
    patch 'customers/information', to:"customers#update"
    get 'customers/unsubscribe', to: "customers#unsubscribe"
    patch 'customers/withdraw', to: "customers#withdraw"

    delete 'cart_items/destroy_all', to: "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
     
    get 'orders/thanks', to: "orders#thanks"
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/confirm', to: "orders#confirm"
    

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    get "search" => "searches#search"
  end

  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :customers, only: [:index, :show, :edit, :update] do
      get 'orders', to: 'orders#customer_index', as: 'customer_orders'
    end
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end
  
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :name, :postal_code, :address, presence: true
  def address_display
    '〒' + self.postal_code + ' ' + self.address + ' ' + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true
  def tax_price
    (self.item.price * 1.1).floor
  end

  def subtotal
    self.tax_price * self.amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :addresses

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :address, presence: true

  validates :postal_code, format: { with: /\A[0-9]+\z/ }
  validates :telephone_number, format: { with: /\A[0-9]+\z/ }

  def active_for_authentication?
    super && is_active == true
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  
  has_many :cart_items
  has_many :order_details
  belongs_to :genre
  
  validates :name, :image, :introduction, :price, presence: true
  validates :is_active, inclusion: { in: [true, false] }
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  scope :genre_search, -> (genre_id) {where(genre_id: genre_id)}

  scope :on_sale, -> {where(is_active: true)}

  def active_status_label
    is_active ? "販売中" : "販売停止中"
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, paid_up: 1, producting: 2, preparing: 3, sented: 4 }

  validates :name, :postal_code, :address, presence: true

  def total_payment
    order_details.sum { |detail| detail.item.price * detail.amount }
  end

  after_update :update_order_detail_status_if_needed

  private

  def update_order_detail_status_if_needed
    if saved_change_to_status? && status == "paid_up"
      self.order_details.update_all(making_status: "pending")
    end
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order


  enum making_status: { unavailable: 0, pending: 1, in_progress: 2, completed: 3 }, _prefix: true

  after_update :update_order_status_if_needed
  after_update :update_order_status_if_all_completed

  private

  # 1つでも制作ステータスを製作中にする⇒注文ステータスを製作中にする
  def update_order_status_if_needed
    if making_status == "in_progress"
      unless order.status == "producting"
        order.update(status: "producting")
      end
    end
  end

  # 全ての製作ステータスを製作完了にする⇒注文ステータスを発送済みにする
  def update_order_status_if_all_completed
    if self.making_status == "completed"
      if order.order_details.all? { |detail| detail.making_status == "completed" }
        order.update(status: "preparing")
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path, notice: 'ジャンルを追加しました。'
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: 'ジャンルを更新しました。'
    else
      flash.now[:alert] = "更新に失敗しました。"
      render :edit
    end
  end

  def destroy
    genre = Genre.find(params[:id])
    genre.destroy
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.order(created_at: :desc).page(params[:page])
    # @order_details = OrderDetail.includes(order: :customer).order(created_at: :desc).page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @genres = Genre.all
    if @item.save
      redirect_to admin_item_path(@item), notice: '商品が登録されました。'
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @genres = Genre.all
    if @item.update(item_params)
      redirect_to admin_item_path(@item), notice: "商品を更新しました。"
    else
      flash.now[:alert] = "更新に失敗しました。"
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id, :price, :image, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :render_404

  private

  def render_404
    render template: 'errors/not_found', status: :not_found
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def genre_search
    @genre_id = params[:genre_id]
    @items = Item.where(genre_id: @genre_id)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container white-bg p-5">
<h4 class="admin-title">ジャンル編集</h4>

  <h4 class="py-5">
    <%= form_with model: [:admin, @genre], local: true do |f| %>
      <div class="d-flex mb-3" style="gap: 80px;">
        <%= f.label :name, "ジャンル名", class: "form-label" %>
        <%= f.text_field :name, style: "width: 275px;" %>
        <%= f.submit "   変更を保存   ", class: "btn btn-success", style: "border-radius: 8px;" %>
      </div>
    <% end %>
  </h4>
</div>

app/views/admin/genres/index.html.erb
<!-- ジャンルの削除機能を一時実装中_View訂正時にRouteとControllerも訂正 -->

<div class="container white-bg p-5">
  <h4 class="admin-title">ジャンル一覧・追加</h4>

  <div class="py-5">
    <h4>
    <%= form_with model: Genre.new, url: admin_genres_path, local: true do |f| %>
      <div class="d-flex align-items-center mb-3" style="gap: 80px;">
        <%= f.label :name, "ジャンル名", class: "form-label" %>
        <%= f.text_field :name, placeholder: "ジャンル名", style: "width: 275px;" %>
        <%= f.submit "     新規登録     ", class: "btn btn-success", style: "border-radius: 8px;" %>
      </div>
    <% end %>
    </h4>
  </div>

  <div style="width: 60%; padding-right: 120px;">
    <table class="table admin-table table-borderless">
      <thead>
        <tr>
          <th style="width: 60%;">ジャンル</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.name %></td>
            <td><%= link_to '編集', edit_admin_genre_path(genre), class: "btn btn-success", style: "border-radius: 8px;" %></td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  
</div>

app/views/admin/items/edit.html.erb
<div class="container white-bg p-5">

<!-- 後日部分テンプレート予定 -->
  <% if @item.errors.any? %>
    <div class="alert alert-danger">
      <h6>以下のエラーがあります：</h6>
      <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h4 class="admin-title">商品編集</h4>
  <div class="row mt-5 ex-admin-table">
    <div class="col-md-8 mx-auto">
      <%= form_with model: [:admin, @item], local: true do |f| %>
        <div class="row mb-3">
          <%= f.label :image, "商品画像", class: "col-sm-3 col-form-label" %>
          <div class="col-sm-9">
            <%= f.file_field :image, id: 'image_input' %>
          </div>
        </div>
        <div class="row mb-3">
          <%= f.label :name, "商品名", class: "col-sm-3 col-form-label" %>
          <div class="col-sm-9">
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>
        <div class="row mb-3">
          <%= f.label :introduction, "商品説明", class: "col-sm-3 col-form-label" %>
            <div class="col-sm-9">
            <%= f.text_area :introduction, rows: 5, class: "form-control" %>
          </div>
        </div>
        <div class="row mb-3">
          <%= f.label :genre_id, "ジャンル", class: "col-sm-3 col-form-label" %>
          <div class="col-sm-9">
            <%= f.collection_select :genre_id, @genres, :id, :name, 
            { prompt: "--選択してください--" }, 
            { class: "form-select", style: "width: 100%;" } %>
          </div>
        </div>
        <div class="row mb-3">
          <%= f.label :price, "税抜価格", class: "col-sm-3 col-form-label" %>
          <div class="col-sm-9">
            <div class="input-group">
              <%= f.text_field :price, class: "form-control" %>円
            </div>
          </div>
        </div>
        <div class="row mb-5">
          <%= f.label :is_active, "販売ステータス", class: "col-sm-3 col-form-label" %>
          <div class="col-sm-9">
            <div class="form-check form-check-inline">
              <%= f.radio_button :is_active, true, id: "active_true", class: "form-check-input" %>
              <%= f.label :is_active_true, "販売中", class: "form-check-label" %>
            </div>
            <div class="form-check form-check-inline">
              <%= f.radio_button :is_active, false, id: "active_false", class: "form-check-input" %>
              <%= f.label :is_active_false, "販売停止中", class: "form-check-label" %>
            </div>
          </div>
        </div>
        <div class="text-center">
          <%= f.submit "変更を保存", class: "btn btn-success btn-lg", style: "border-radius: 8px;" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container white-bg p-5">
  <h4 class="admin-title">商品一覧</h4>

    <div class="add-btn">
      <%= link_to new_admin_item_path do %>
        <%= image_tag 'add_new_item.png', style: "width: 100px;" %>
      <% end %>
    </div>

  <table class="table mt-5 admin-table table-borderless">
    <thead>
      <tr>
        <th style="width: 10%;">商品ID</th>
        <th style="width: 30%;">商品名</th>
        <th style="width: 10%;">税抜価格</th>
        <th style="width: 30%;">ジャンル</th>
        <th style="width: 20%;">ステータス</th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><u><%= link_to item.name, admin_item_path(item), class: "text-dark" %></u></td>
          <td><%= number_to_currency(item.price, unit: "", precision: 0) %></td>
          <td><%= item.genre.name %></td>
          <td class="<%= item.is_active ? "text-success font-weight-bold" : "text-secondary font-weight-bold" %>">
            <%= item.is_active ? "販売中" : "販売停止中" %>
          </td>
        </tr>
      <% end %>

    </tbody>
  </table>
  <div class="d-flex justify-content-center mt-2">
    <%= paginate @items %>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container white-bg p-5">

<!-- 後日部分テンプレート予定 -->
  <% if @item.errors.any? %>
    <div class="alert alert-danger">
      <h6>以下のエラーがあります：</h6>
      <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h4 class="admin-title">商品新規登録</h4>
  <div class="row mt-5 ex-admin-table">
    <div class="col-md-8 mx-auto">
      <%= form_with model: @item, local: true, html: { multipart: true }, url: admin_items_path do |f| %>
        <div class="row mb-3">
          <%= f.label :image, "商品画像", class: "col-md-3 col-form-label" %>
          <div class="col-md-9">
            <%= f.file_field :image, id: 'image_input' %>
          </div>
        </div>
        <div class="row mb-3">
          <%= f.label :name, "商品名", class: "col-md-3 col-form-label" %>
          <div class="col-md-9">
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>
        <div class="row mb-3">
          <%= f.label :introduction, "商品説明", class: "col-md-3 col-form-label" %>
            <div class="col-md-9">
            <%= f.text_area :introduction, rows: 5, class: "form-control" %>
          </div>
        </div>
        <div class="row mb-3">
          <%= f.label :genre_id, "ジャンル", class: "col-md-3 col-form-label" %>
          <div class="col-md-9">
            <%= f.collection_select :genre_id, @genres, :id, :name, 
            { prompt: "--選択してください--" }, 
            { class: "form-select", style: "width: 100%;" } %>
          </div>
        </div>
        <div class="row mb-3">
          <%= f.label :price, "税抜価格", class: "col-md-3 col-form-label" %>
          <div class="col-md-9">
            <div class="input-group">
              <%= f.text_field :price, class: "form-control" %>円
            </div>
          </div>
        </div>
        <div class="row mb-4">
          <%= f.label :is_active, "販売ステータス", class: "col-md-3 col-form-label" %>
          <div class="col-md-9">
            <div class="form-check form-check-inline">
              <%= f.radio_button :is_active, true, id: "active_true", class: "form-check-input" %>
              <%= f.label :is_active_true, "販売中", class: "form-check-label" %>
            </div>
            <div class="form-check form-check-inline">
              <%= f.radio_button :is_active, false, id: "active_false", class: "form-check-input" %>
              <%= f.label :is_active_false, "販売停止中", class: "form-check-label" %>
            </div>
          </div>
        </div>
        <div class="text-center">
          <%= f.submit "新規登録", class: "btn btn-success btn-lg", style: "border-radius: 8px;" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container white-bg p-5">
  <h4 class="admin-title">商品詳細</h4>
  <div class="row mt-5">
    <div class="col-md-4">
      <%= image_tag url_for(@item.image), class: "img-thumbnail", style: "width: 300px; height: 200px; object-fit: cover;" %>
    </div>

    <div class="col-md-8 ex-admin-table">
      <table class="table" style="border: none;">
        <tr>
          <th style="width: 30%; border: none; font-weight: normal;">商品名</th>
          <td style="width: 70%; border: none; font-size: 1.2em;"><%= @item.name %></td>
        </tr>
        <tr>
          <th style="border: none; font-weight: normal;">商品説明</th>
          <td style="border: none; font-size: 1.2em;"><%= truncate(@item.introduction, length: 170) %></td>
        </tr>
        <tr>
          <th style="border: none; font-weight: normal;">ジャンル</th>
          <td style="border: none; font-size: 1.2em;"><%= @item.genre.name %></td>
        </tr>
        <tr>
          <th style="border: none; font-weight: normal;">税込価格<br>(税抜価格)</th>
          <td style="border: none; font-size: 1.2em;"><%= number_to_currency(@item.price * 1.1, unit: "", delimiter: ",", precision: 0) %> (<%= number_to_currency(@item.price, unit: "", delimiter: ",", precision: 0) %>円)</td>
        </tr>
        <tr>
          <th style="border: none; font-weight: normal;">販売ステータス</th>
          <td style="border: none; font-size: 1.2em;">
            <div class="<%= @item.is_active ? 'text-success font-weight-bold' : 'text-secondary font-weight-bold' %>">
              <%= @item.is_active ? "販売中" : "販売停止中" %>
            </div>
          </td>
        </tr>
      </table>
    </div>
  </div>

  <div class="d-flex justify-content-center">
    <%= link_to '編集する', edit_admin_item_path(@item), class: "btn btn-success btn-lg", style: "border-radius: 8px;" %>
  </div>
</div>