config/routes.rb
Rails.application.routes.draw do

   # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], path: '', controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
   devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
     sessions: "admin/sessions"
   }
  
  
  scope module: :public do
    root to: 'homes#top'
    get 'about', to: "homes#about"

    resources :items, only: [:index, :show]

    get 'customers/my_page', to:"customers#show"
    get 'customers/information/edit', to:"customers#edit"
    patch 'customers/information', to:"customers#update"
    get 'customers/unsubscribe', to: "customers#unsubscribe"
    patch 'customers/withdraw', to: "customers#withdraw"

    delete 'cart_items/destroy_all', to: "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
     
    get 'orders/thanks', to: "orders#thanks"
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/confirm', to: "orders#confirm"
    

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    get "search" => "searches#search"
  end

  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :customers, only: [:index, :show, :edit, :update] do
      get 'orders', to: 'orders#customer_index', as: 'customer_orders'
    end
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end
  
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :name, :postal_code, :address, presence: true
  def address_display
    '〒' + self.postal_code + ' ' + self.address + ' ' + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true
  def tax_price
    (self.item.price * 1.1).floor
  end

  def subtotal
    self.tax_price * self.amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :addresses

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :address, presence: true

  validates :postal_code, format: { with: /\A[0-9]+\z/ }
  validates :telephone_number, format: { with: /\A[0-9]+\z/ }

  def active_for_authentication?
    super && is_active == true
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  
  has_many :cart_items
  has_many :order_details
  belongs_to :genre
  
  validates :name, :image, :introduction, :price, presence: true
  validates :is_active, inclusion: { in: [true, false] }
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  scope :genre_search, -> (genre_id) {where(genre_id: genre_id)}

  scope :on_sale, -> {where(is_active: true)}

  def active_status_label
    is_active ? "販売中" : "販売停止中"
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, paid_up: 1, producting: 2, preparing: 3, sented: 4 }

  validates :name, :postal_code, :address, presence: true

  def total_payment
    order_details.sum { |detail| detail.item.price * detail.amount }
  end

  after_update :update_order_detail_status_if_needed

  private

  def update_order_detail_status_if_needed
    if saved_change_to_status? && status == "paid_up"
      self.order_details.update_all(making_status: "pending")
    end
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order


  enum making_status: { unavailable: 0, pending: 1, in_progress: 2, completed: 3 }, _prefix: true

  after_update :update_order_status_if_needed
  after_update :update_order_status_if_all_completed

  private

  # 1つでも制作ステータスを製作中にする⇒注文ステータスを製作中にする
  def update_order_status_if_needed
    if making_status == "in_progress"
      unless order.status == "producting"
        order.update(status: "producting")
      end
    end
  end

  # 全ての製作ステータスを製作完了にする⇒注文ステータスを発送済みにする
  def update_order_status_if_all_completed
    if self.making_status == "completed"
      if order.order_details.all? { |detail| detail.making_status == "completed" }
        order.update(status: "preparing")
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.order(created_at: :desc).page(params[:page])
    # @order_details = OrderDetail.includes(order: :customer).order(created_at: :desc).page(params[:page]).per(10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :render_404

  private

  def render_404
    render template: 'errors/not_found', status: :not_found
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def genre_search
    @genre_id = params[:genre_id]
    @items = Item.where(genre_id: @genre_id)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer style="background-color: #f4bb77;" class="text-dark text-center py-3">
  <div class="container">
    <p class="mb-0" style="font-weight: bold;"> </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="custom-header">
  <nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: ">
    <div class="container-fluid">
      <div class="ml-5 pl-5">
        <a class="navbar-brand ml-5 pl-5" href="/">
          <img src="/assets/logo_top.png" alt="NaganoCake Logo" height="100">
        </a>
      </div>
      
      <% if admin_signed_in? %> 
        <div class="d-flex flex-column align-items-end mr-5 pr-5 header_menu">
          <ul class="list-unstyled">
            <div class="d-flex ">
              <li class="mr-5 ">
                <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-brown  w-100 px-3 py-2" %>
              </li>
              <li class="mr-5">
                <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-brown  w-100 px-3 py-2" %>
              </li>
              <li class="mr-5">
                <%= link_to "注文履歴一覧", admin_root_path, class: "btn btn-outline-brown  w-100 px-3 py-2"%>
              </li>
              <li class="mr-5">
                <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-brown  w-100 px-3 py-2"%>
              </li>
              <li class="mr-5">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-brown  w-100 px-3 py-2" %>
              </li>
          </ul>
          <%= form_with url: search_path, method: :get, local: true, class: "form-inline my-1 my-lg-0" do |f| %>
            <div class="input-group mr-5">
              <%= f.text_field :word, class: "form-control input-brown", placeholder: "キーワードを入力" %>
              <div class="input-group-append">
                <button class="btn btn-outline-brown" type="submit">
                  <i class="fa-solid fa-magnifying-glass"></i>
                </button>
              </div>
            </div>
          <% end %>
        </div>
        
          
      <% elsif customer_signed_in?  %>
          <div class="mr-5 mt-4">
            <h4>ようこそ <%= current_customer.last_name %>さん</4>
          </div>
          <div class="d-flex flex-column align-items-end mr-5 pr-5 header_menu">
            <ul class="list-unstyled">
              <div class="d-flex ">
                <li class="mr-5 ">
                  <%= link_to "マイページ", customers_my_page_path, class: "btn btn-outline-brown  w-100 px-3 py-2" %>
                </li>
                <li class="mr-5">
                  <%= link_to "商品一覧", items_path, class: "btn btn-outline-brown  w-100 px-3  py-2" %>
                </li>
                <li class="mr-5">
                  <%= link_to "カート", cart_items_path, class: "btn btn-outline-brown  w-100 px-3 py-2" %>
                </li>
                <li class="mr-5">
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-brown  w-100 px-3 py-2" %>
                </li>
            </ul>
            <%= form_with url: search_path, method: :get, local: true, class: "form-inline my-1 my-lg-0" do |f| %>
              <div class="input-group mr-5">
                <%= f.text_field :word, class: "form-control input-brown", placeholder: "キーワードを入力" %>
                <div class="input-group-append">
                  <button class="btn btn-outline-brown" type="submit">
                    <i class="fa-solid fa-magnifying-glass"></i>
                  </button>
                </div>
              </div>
            <% end %>
          </div>
           
      <% else %>
        <div class="d-flex flex-column align-items-end mr-5 pr-5 header_menu">
          <ul class="list-unstyled">
            <div class="d-flex ">
              <li class="mr-5 ">
                <%= link_to "アバウト", about_path, class: "btn btn-outline-brown  w-100 px-3 py-2" %>
              </li>
              <li class="mr-5">
                <%= link_to "商品一覧", items_path, class: "btn btn-outline-brown  w-100 px-3 py-2" %>
              </li>
              <li class="mr-5">
                <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-brown  w-100 px-3 py-2" %>
              </li>
              <li class="mr-5">
                <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-brown  w-100 px-3 py-2" %>
              </li>
          </ul>
          <%= form_with url: search_path, method: :get, local: true, class: "form-inline my-1 my-lg-0" do |f| %>
            <div class="input-group mr-5">
              <%= f.text_field :word, class: "form-control input-brown", placeholder: "キーワードを入力" %>
              <div class="input-group-append">
                <button class="btn btn-outline-brown" type="submit">
                  <i class="fa-solid fa-magnifying-glass"></i>
                </button>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/1bfff810b3.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Decol&family=Kaisei+Opti&family=Philosopher:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    
  </head>

<body class="d-flex flex-column min-vh-100">
  <%= render 'layouts/header' %>

  <main class="flex-grow-1">
    <%= yield %>
  </main>

  <%= render 'layouts/footer' %>
</body>

</html>